#!/usr/bin/env bash
# Write the commits on branch "ocelot" in build/src (since the pinned tag) back to
# patches/, one file per commit, and regenerate patches/series in commit order.
#
# Every commit needs an "Ocelot-Patch: <area>/<name>" trailer naming its patch file
# (patches/<area>/<name>.patch). Add one with:
#   git commit --amend --trailer "Ocelot-Patch: web/math-delimiters"
source "$(dirname "$0")/lib.sh"

[ -e "$SRC/.git" ] || die "no build/src; run scripts/apply.sh first"
cd "$SRC"
[ ! -d "$(git rev-parse --git-path rebase-apply)" ] || die "git am in progress in build/src; finish it first"
[ "$(git branch --show-current)" = "$BRANCH" ] || die "build/src is not on branch $BRANCH"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
names=()

for commit in $(git rev-list --reverse "$UPSTREAM..$BRANCH"); do
  name=$(git log -1 --format='%(trailers:key=Ocelot-Patch,valueonly,separator=)' "$commit" | tr -d '[:space:]')
  [ -n "$name" ] || die "commit $(git log -1 --format='%h %s' "$commit") has no Ocelot-Patch trailer"
  case " ${names[*]-} " in *" $name "*) die "two commits use Ocelot-Patch: $name" ;; esac
  names+=("$name")
  mkdir -p "$tmp/$(dirname "$name")"
  git format-patch -q -1 -k --zero-commit --no-signature --no-stat --stdout "$commit" > "$tmp/$name.patch"
done

# Replace patches/ wholesale so deleted or renamed patches disappear.
find "$ROOT/patches" -name '*.patch' -delete
find "$ROOT/patches" -mindepth 1 -type d -empty -delete
cp -r "$tmp"/. "$ROOT/patches/" 2>/dev/null || true
{
  echo "# Generated by scripts/export.sh from build/src (branch $BRANCH). Applied in order."
  for name in "${names[@]+"${names[@]}"}"; do echo "$name.patch"; done
} > "$ROOT/patches/series"

log "exported ${#names[@]} patches"
git -C "$ROOT" status --short -- patches
